version: 2.1

jobs:
  lint-app:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
  build-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker container for each microservices
          command: |
            echo "--------- Installing dependencies-----------"
            sudo curl -LO https://nodejs.org/dist/v18.0.0/node-v18.0.0-linux-x64.tar.xz
            sudo tar -xvf node-v18.0.0-linux-x64.tar.xz
            sudo cp -r node-v18.0.0-linux-x64/{bin,include,lib,share} /usr/
            node --version => v18.0.0
            sudo apt install nodejs
            echo "--------- The images is Building ------------"
            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed justus20/udagram-api-feed:v0
            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user justus20/udagram-api-user:v0
            
            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend justus20/udagram-frontend:v0
            docker build -t udagram-reverseproxy ./udagram-reverseproxy
            docker tag udagram-reverseproxy justus20/udagram-reverseproxy:v0
            echo "-------- All images succesfully built----------"
            
            echo " ------- login in to hub--------"
            docker login -u justus20 -p $DOCKERPASS
            echo "-------------- Pushing images to dockerhub-------"
            docker push justus20/udagram-api-feed:v0
            docker push justus20/udagram-api-user:v0
            docker push justus20/udagram-frontend:v0
            docker push justus20/udagram-reverseproxy:v0
workflows:
  default:
    jobs:
      - lint-app
      - build-docker:
          requires: [lint-app]